### ISSUE TITLE
How to train a custom model?

### ISSUE THREAD

**Issue by technoartista** [IBM/MAX-Object-Detector-Web-App#12]
is it possible to train a custom model in this docker container? Or use a pretrained tensorflow model ?

**Comment by stevemart** [comment]
Hi @technoartista the model used here is built from the [COCO dataset](http://mscoco.org/) and Tensorflow models here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

For more information about the MAX model, go to https://github.com/IBM/MAX-Object-Detector

@ajbozarth please feel free to chime in.

**Comment by ajbozarth** [comment]
What @stevemart said, the best place to ask this quest would be on the model itself that Steve linked. Then the MAX devs would be able to give better feedback. But the short answer is "not currently"
