### ISSUE TITLE
Real-time object detection - Can't use videos 

### ISSUE THREAD

**Issue by NewProgUser** [IBM/MAX-Object-Detector-Web-App#22]
I want to do real-time object detection using this project. In the input tag if I add extensions like .mp4, .avi or any other video extension, the file doesn't get processed for object detection and the API doesn't return any prediction on that. Any Idea how can I change this project from static object detection to real-time object detection?
Any kind of help would be very appreciated

**Comment by ajbozarth** [comment]
This particular web app was written as a simple wrapper around our Object Detection model with only takes in Images. We do have another code pattern web app using our facial age estimator model that does what you're talking about. We have considered taking the time to adapt it for other models like object detector if you want to start there.

**Comment by ajbozarth** [comment]
Facial Age Estimator Web App: https://github.com/IBM/MAX-Facial-Age-Estimator-Web-App

Facial Age Estimator Web App using tf.js: https://github.com/IBM/fae-tfjs
