### ISSUE TITLE
YouTube video link is broken

### ISSUE THREAD

**Issue by ahmedmostafaalsayed** [IBM/MAX-Object-Detector-Web-App#32]
The video link (https://www.youtube.com/watch?v=Hs6sVWmfVFw) on [Create a web app to visually interact with objects detected using machine learning](https://github.com/IBM/MAX-Object-Detector-Web-App/blob/master/README.md) is broken. Please update the link.

**Comment by bdwyer2** [comment]
@ajbozarth

**Comment by ajbozarth** [comment]
Thanks for the heads up, we're looking into what happened to the video. I still have the original video file so worst case we re-upload it elsewhere.

**Comment by ptitzler** [comment]
We've received confirmation that the youtube channel was deleted. We will re-upload the video to a new location and update the broken link(s) as necessary. Thanks for reporting the problem, this one slipped through!

**Comment by ptitzler** [comment]
Note that the corresponding link in the code pattern https://developer.ibm.com/patterns/create-a-web-app-to-interact-with-objects-detected-using-machine-learning/ is also broken

**Comment by ptitzler** [comment]
Confirmed that the link in the code pattern is now also fixed
