### ISSUE TITLE
Write a Blog Post

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Object-Detector-Web-App#6]
We need to write a blog post about the creation process of this code pattern for publishing on the IBM Code Blog. 

We can also work with @ptitzler to create a sister blog post for our Medium blog.

**Comment by ajbozarth** [comment]
I've written up a rough draft of the blog for review: http://developer.ibm.com/code/?p=41030&preview=1&_ppp=c7efc68a2e

This time around I wrote the blog about my process, how the app came to be rather than a walk through of how it works. I wouldn't be surprised if it needs revision given I just wrote it up yesterday and then proof read it today. 

Feel free to post feedback here (since feedback on a WP blog is not a thing) and I'll address it when I return from vacation next week (I'll be unavailable Thurs-Sun).

**Comment by ajbozarth** [comment]
@stevemart @rhagarty @ptitzler @gdequeiroz @djalova @MLnick each of you has helped me review written content in the past if you'd be willing to take a look at my blog above. If you get me feedback today I'll try to address it before I leave tonight.

**Comment by gdequeiroz** [comment]
Typo in the second sentence: **Machine leaning** engines like ...

**Comment by ajbozarth** [comment]
wow, the first two paragraphs were copied from my previous blog, I'll fix that in both >.<

**Comment by ajbozarth** [comment]
@gdequeiroz thanks, I've fixed the typos

**Comment by ajbozarth** [comment]
Note: as @ptitzler found, word press doesn't seem to be propagating all my updates, but they are fixed, trust me

**Comment by ptitzler** [comment]
Nice write-up. I like the personal style.

**Comment by djalova** [comment]
I think this sentence needs a colon
`This brought me to my first roadblock when creating my wrapper: how to send an image to the model API for prediction.`

**Comment by ajbozarth** [comment]
Thanks @djalova I went back and forth when typing that if it should be a colon or comma.

Also the new preview link is: http://developer.ibm.com/code/?p=41030&preview=1&_ppp=0d54bd8773
and all my updates are now visible there

**Comment by ajbozarth** [comment]
Thanks for all the feedback everyone. If @stevemart and @rhagarty think the blog looks good then I'll close this issue as complete and leave any further review to the publishing team.

**Comment by stevemart** [comment]
I meant to take a look at it, give me til EOD

**Comment by stevemart** [comment]
@ajbozarth i think "frustration" is a bit strong in these sentences:

```
Continuing from my previous work, I was interested in creating another interesting application based on a MAX model. While researching and testing different models available on MAX there was one model that frustrated me. The Object Detector model seemed like it could be interesting but the JSON output was difficult to visualize in my head. My frustration prompted me to start creating a small visual wrapper for the model, which eventually grew into a fully functioning web application.
```

```
Continuing from my previous work, I was interested in creating another interesting application based on a MAX model. While researching and testing different models available on MAX there was one model that I felt could be improved. The Object Detector model seemed like it could be interesting but the JSON output was difficult to visualize in my head. This prompted me to start creating a small visual wrapper for the model, which eventually grew into a fully functioning web application.
```

**Comment by stevemart** [comment]
@ajbozarth i'd also try to avoid using the term wrapper too many times, don't diminish your work! 

This is a fantastic blog, thank you for writing it. It's very engaging and kept me interested.

**Comment by ajbozarth** [comment]
I'll reevaluate the word `frustration` in those sections, what softer word would you suggest? And the reason I used wrapper was to distinguish the initial app and intended plan, "just a wrapper" in comparison to the final version which is a solid web app

**Comment by stevemart** [comment]
@ajbozarth see original comment for suggest re-wording. For the record, both comments are super nit picky and don't need to be fixed.

**Comment by ajbozarth** [comment]
Ah, didn't notice the second block was a suggested change >.<

**Comment by ajbozarth** [comment]
and thanks for the feedback @stevemart I'll mull over those changes today. Since the rough draft is ready for publishing to review I'll close this for now.
